apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts: 
  - reviews
  subsets:
  - name: v1
    labels:
      version: v1
  
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 100
        http:
          http2MaxRequests: 1000
          maxRequestsPerConnection: 10
      outlierDetection:
        consecutiveErrors: 7
        interval: 5m
        baseEjectionTime: 15m
